### ISSUE TITLE
ao.bind anonymous - no context Error: CLS NOT ACTIVE  for mssql -  generic pool support might be outdated

### ISSUE THREAD

**Issue by twiggy** [appoptics/appoptics-apm-node#15]
appoptics:warn ao.bind anonymous - no context Error: CLS NOT ACTIVE
    at Object.exports.bind (/xxxxx/node_modules/appoptics-apm/dist/index.js:618:17)
    at Pool.aaabbb (/xxxxx/node_modules/appoptics-apm/dist/probes/generic-pool.js:27:31)
    at ConnectionPool._acquire (/xxxxxx/node_modules/mssql/lib/base.js:184:22)
    at ConnectionPool.acquire (/xxxxxx/node_modules/mssql/lib/base.js:172:12)
    at Immediate._query.err (/xxxxx/node_modules/mssql/lib/tedious.js:554:19)
    at Immediate.<anonymous> (/xxxxx/node_modules/async-listener/glue.js:188:31)

Get this when my app starts up an every database call. Also, don't get any kind of db tracing.

node-mssql 4.0.1 uses tedious which seems in your supported range. It also use generic-pool 3.4.2 ( as of today ). I think you have generic pool support, but it seems quite old.

I changed generic-pool.js which is why you see pool.aaabbb and not pool anonymous. I couldn't quite figure out what function clsCheck() does, but i think its returning false.

**Comment by bmacnaughton** [comment]
We don't currently support generic-pool versions >= 3. I'll take a look at this.

**Comment by bmacnaughton** [comment]
v5.4.1 supports generic-pool v3.
