### ISSUE TITLE
error output with tedious.js

### ISSUE THREAD

**Issue by twiggy** [appoptics/appoptics-apm-node#20]
`appoptics:error ao.runInstrument failed to build span TypeError: Cannot read property 'value' of undefined
    at ao.instrument.args.(anonymous function).userCallback (/home/folder/baseplate/node_modules/appoptics-apm/dist/probes/tedious.js:37:56)
    at runInstrument (/home/folder/baseplate/node_modules/appoptics-apm/dist/index.js:734:45)
    at Object.exports.instrument (/home/folder/baseplate/node_modules/appoptics-apm/dist/index.js:1124:14)
    at Connection.<anonymous> (/home/folder/baseplate/node_modules/appoptics-apm/dist/probes/tedious.js:36:17)
    at Connection.callProcedure (/home/folder/baseplate/node_modules/tedious/lib/connection.js:1293:12)
    at parent.acquire (/home/folder/baseplate/node_modules/mssql/lib/tedious.js:1022:20)
    at _acquire.then.connection (/home/folder/baseplate/node_modules/mssql/lib/base.js:172:42)
    at <anonymous> +10ms
`
The app seems to be working and sql calls are being logged. setting ao.errorlevel = '' for now, but would rather know these are happening. would get flooded though. might be nice to write these into something other than standard out.

Thanks in advance.

**Comment by bmacnaughton** [comment]
node-mssql 4.0.1 uses tedious
node version 8.11.3

**Comment by bmacnaughton** [comment]
Any chance you can determine which queries cause this error? Our tests, while not exhaustive, don't encounter it so the query and parameters might be useful.

**Comment by bmacnaughton** [comment]
@twiggy - The code in question has been completely reworked since this bug report. Can you verify that there is/isn't a problem with current versions of the agent?

**Comment by cheempz** [comment]
Closing, please feel free to reopen if this is still a problem.
