### ISSUE TITLE
mongoose issues 

### ISSUE THREAD

**Issue by Igor-Techsee** [appoptics/appoptics-apm-node#43]
os - ubuntu 14.04
node version - 6.9.4
stack trace from error -

appoptics:warn ao.bind - no context Error: CLS NOT ACTIVE
at Object.exports.bind (/***/node_modules/appoptics-apm/lib/index.js:638:17)
at Query._wrapCallback (/***/node_modules/appoptics-apm/lib/probes/mongoose.js:91:37)
at Query.findOne (/***/node_modules/mquery/lib/mquery.js:1811:19)
at Query._findOne (/***/node_modules/mongoose/lib/query.js:1522:22)
at /***/node_modules/kareem/index.js:250:8
at /***/node_modules/kareem/index.js:23:7
at _combinedTickCallback (internal/process/next_tick.js:67:7)
at process._tickDomainCallback (internal/process/next_tick.js:122:9)

**Comment by Igor-Techsee** [comment]
1. every mongoose call 
2. we use mongodb 3.4 with following npm packages:
       "mongodb": "2.2.34",
        "mongodb-migrate": "2.0.2",
        "mongoose": "4.13.14",
        "mongoose-deep-populate": "2.0.3",
        "mongoose-field-encryption": "0.0.5"
3. "appoptics-apm": "5.9.0"

**Comment by bmacnaughton** [comment]
thank you. i appreciate your help.

are you using mongoose with promises as opposed to callbacks?

**Comment by Igor-Techsee** [comment]
thanks, I"ll try this version next week

**Comment by Igor-Techsee** [comment]
still same issue : 
 2018-12-27T12:30:37.043Z appoptics:warn ao.bind() - no context Error: CLS NOT ACTIVE
at Object.exports.bind (/var/www/techsee-api/node_modules/appoptics-apm/lib/index.js:638:17)
at model.Query._wrapCallback (/var/www/techsee-api/node_modules/appoptics-apm/lib/probes/mongoose.js:112:37)
at model.Query.Query.findOne (/var/www/techsee-api/node_modules/mquery/lib/mquery.js:1811:19)
at model.Query.Query._findOne (/var/www/techsee-api/node_modules/mongoose/lib/query.js:1522:22)
at /var/www/techsee-api/node_modules/kareem/index.js:250:8
at /var/www/techsee-api/node_modules/kareem/index.js:23:7
at _combinedTickCallback (internal/process/next_tick.js:132:7)
at process._tickDomainCallback (internal/process/next_tick.js:219:9)

same error also on node v8.12 ...

**Comment by Igor-Techsee** [comment]
I see warnings also on 'mongoose-deep-populate' related queries : 
 2018-12-27T12:45:10.468Z appoptics:warn ao.bind(anonymous) - no context Error: CLS NOT ACTIVE
at Object.exports.bind (/var/www/techsee-api/node_modules/appoptics-apm/lib/index.js:638:17)
at model.Query.<anonymous> (/var/www/techsee-api/node_modules/appoptics-apm/lib/probes/mongoose.js:102:42)
at model.Query.Query.exec (/var/www/techsee-api/node_modules/mongoose-deep-populate/lib/plugin.js:49:20)
at model.Query.Query.then (/var/www/techsee-api/node_modules/mongoose/lib/query.js:3147:15)
at Object.getById (/var/www/techsee-api/server/models/room.js:581:14)

**Comment by bmacnaughton** [comment]
@Igor-Techsee - thanks for checking this out and I'm sorry it didn't fix the issue for you. I have a couple questions:

> /var/www/techsee-api/node_modules/kareem/index.js:250:8
could you expand a bit on how you're using kareem? we test `findOne` specifically and, at least in our tests, we manage to maintain context. So, based on the stack trace, it seems that context has been lost before `Query.Query._findOne()` is being called.

also, are you seeing these only on `findOne()` calls or are you seeing them on `add()` calls as well?

> I see warnings also on 'mongoose-deep-populate' related queries 
thanks for this. we currently don't test any plug-ins for mongoose. I'll add a test and see if I can find a problem. If you have any details on how you use it I'll try to test for that specific case.

**Comment by Igor-Techsee** [comment]
> > it happens on every call
> 
> I just want to confirm that this is running in an http/https server context.

It happens on every findOne, in dashboard I can see find/update queries
