### ISSUE TITLE
appoptics:error Can't load bindings Error'

### ISSUE THREAD

**Issue by lorenzfleerackers** [appoptics/appoptics-apm-node#62]
When i start my application i receive this error : "appoptics:error Can't load bindings Error: Cannot find module 'appoptics-bindings'"

Can someone help me?

Kind regards 
Lorenz Fleerackers

**Comment by cheempz** [comment]
Hi @lorenzfleerackers, that generally means something went wrong during agent install when it tries to build an addon (a.k.a the bindings).  Note that there are some system dependencies required:

https://docs.appoptics.com/kb/apm_tracing/nodejs/install/#dependencies

If the above are satisfied and you're still getting the error, could you do the following and provide the output to help us diagnose:

* `node -v` - node version
* `npm ls --json` - list of all node packages in json format
* `lsb_release -a` - OS version
* enable extra output via `export APPOPTICS_SHOW_OBOE_SETUP=1`, then run `npm install` in the appoptics-bindings directory.

**Comment by bmacnaughton** [comment]
@lorenzfleerackers - if you're still having the problem please feel free to re-open this.

**Comment by gtilma** [comment]
Request to reopen this issue; getting the following error on AWS Elastic Beanstalk:
```
2019-05-16T15:19:57.871Z appoptics:error Can't load bindings Error: /var/app/current/node_modules/appoptics-bindings/build/Release/appoptics-bindings.node: undefined symbol: napi_module_register
    at Error (native)
    at Object.Module._extensions..node (module.js:597:18)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at bindings (/var/app/current/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/var/app/current/node_modules/appoptics-bindings/index.js:1:99)
    at Module._compile (module.js:570:32)
2019-05-16T15:19:57.893Z appoptics:error AppopticsAPM disabled due to: require failed:
```

Have verified OS-level dependencies listed at https://docs.appoptics.com/kb/apm_tracing/nodejs/install/#dependencies.

`node -v`
v6.12.2

`npm ls --json` (relevant snippet)
```
    "appoptics-apm": {
      "version": "6.4.0",
      "from": "appoptics-apm@>=6.4.0 <7.0.0",
      "resolved": "https://registry.npmjs.org/appoptics-apm/-/appoptics-apm-6.4.0.tgz",
      "dependencies": {
        "appoptics-bindings": {
          "version": "6.2.1",
          "from": "appoptics-bindings@>=6.2.1 <7.0.0",
          "resolved": "https://registry.npmjs.org/appoptics-bindings/-/appoptics-bindings-6.2.1.tgz",
          "dependencies": {
            "bindings": {
              "version": "1.2.1",
              "from": "bindings@>=1.2.1 <1.3.0",
              "resolved": "https://registry.npmjs.org/bindings/-/bindings-1.2.1.tgz"
            },
            "linux-os-info": {
              "version": "2.0.0",
              "from": "linux-os-info@>=2.0.0 <3.0.0",
              "resolved": "https://registry.npmjs.org/linux-os-info/-/linux-os-info-2.0.0.tgz"
            },
            "node-addon-api": {
              "version": "1.6.3",
              "from": "node-addon-api@>=1.6.3 <2.0.0",
              "resolved": "https://registry.npmjs.org/node-addon-api/-/node-addon-api-1.6.3.tgz"
            },
            "node-gyp": {
              "version": "4.0.0",
              "from": "node-gyp@>=4.0.0 <5.0.0",
              "resolved": "https://registry.npmjs.org/node-gyp/-/node-gyp-4.0.0.tgz",
              "dependencies": {
                "semver": {
                  "version": "5.3.0",
                  "from": "semver@>=5.3.0 <5.4.0",
                  "resolved": "https://registry.npmjs.org/semver/-/semver-5.3.0.tgz"
                },
                "nopt": {
                  "version": "3.0.6",
                  "from": "nopt@>=2.0.0 <3.0.0||>=3.0.0 <4.0.0",
                  "resolved": "https://registry.npmjs.org/nopt/-/nopt-3.0.6.tgz",
                  "dependencies": {
                    "abbrev": {
                      "version": "1.1.1",
                      "from": "abbrev@>=1.0.0 <2.0.0",
                      "resolved": "https://registry.npmjs.org/abbrev/-/abbrev-1.1.1.tgz"
                    }
                  }
                },
                "npmlog": {
                  "version": "4.1.2",
                  "from": "npmlog@>=0.0.0 <1.0.0||>=1.0.0 <2.0.0||>=2.0.0 <3.0.0||>=3.0.0 <4.0.0||>=4.0.0 <5.0.0",
                  "resolved": "https://registry.npmjs.org/npmlog/-/npmlog-4.1.2.tgz",
                  "dependencies": {
                    "are-we-there-yet": {
                      "version": "1.1.5",
                      "from": "are-we-there-yet@>=1.1.2 <1.2.0",
                      "resolved": "https://registry.npmjs.org/are-we-there-yet/-/are-we-there-yet-1.1.5.tgz",
                      "dependencies": {
                        "delegates": {
                          "version": "1.0.0",
                          "from": "delegates@>=1.0.0 <2.0.0",
                          "resolved": "https://registry.npmjs.org/delegates/-/delegates-1.0.0.tgz"
                        }
                      }
                    },
                    "console-control-strings": {
                      "version": "1.1.0",
                      "from": "console-control-strings@>=1.1.0 <1.2.0",
                      "resolved": "https://registry.npmjs.org/console-control-strings/-/console-control-strings-1.1.0.tgz"
                    },
                    "gauge": {
                      "version": "2.7.4",
                      "from": "gauge@>=2.7.3 <2.8.0",
                      "resolved": "https://registry.npmjs.org/gauge/-/gauge-2.7.4.tgz",
                      "dependencies": {
                        "aproba": {
                          "version": "1.2.0",
                          "from": "aproba@>=1.0.3 <2.0.0",
                          "resolved": "https://registry.npmjs.org/aproba/-/aproba-1.2.0.tgz"
                        },
                        "has-unicode": {
                          "version": "2.0.1",
                          "from": "has-unicode@>=2.0.0 <3.0.0",
                          "resolved": "https://registry.npmjs.org/has-unicode/-/has-unicode-2.0.1.tgz"
                        },
                        "signal-exit": {
                          "version": "3.0.2",
                          "from": "signal-exit@>=3.0.0 <4.0.0",
                          "resolved": "https://registry.npmjs.org/signal-exit/-/signal-exit-3.0.2.tgz"
                        },
                        "wide-align": {
                          "version": "1.1.3",
                          "from": "wide-align@>=1.1.0 <2.0.0",
                          "resolved": "https://registry.npmjs.org/wide-align/-/wide-align-1.1.3.tgz"
                        }
                      }
                    }
                  }
                },
                "osenv": {
                  "version": "0.1.5",
                  "from": "osenv@>=0.0.0 <1.0.0",
                  "resolved": "https://registry.npmjs.org/osenv/-/osenv-0.1.5.tgz"
                },
                "rimraf": {
                  "version": "2.6.3",
                  "from": "rimraf@>=2.0.0 <3.0.0",
                  "resolved": "https://registry.npmjs.org/rimraf/-/rimraf-2.6.3.tgz"
                },
                "tar": {
                  "version": "4.4.8",
                  "from": "tar@>=4.4.8 <5.0.0",
                  "resolved": "https://registry.npmjs.org/tar/-/tar-4.4.8.tgz",
                  "dependencies": {
                    "chownr": {
                      "version": "1.1.1",
                      "from": "chownr@>=1.1.1 <2.0.0",
                      "resolved": "https://registry.npmjs.org/chownr/-/chownr-1.1.1.tgz"
                    },
                    "fs-minipass": {
                      "version": "1.2.6",
                      "from": "fs-minipass@>=1.2.5 <2.0.0",
                      "resolved": "https://registry.npmjs.org/fs-minipass/-/fs-minipass-1.2.6.tgz"
                    },
                    "minipass": {
                      "version": "2.3.5",
                      "from": "minipass@>=2.3.4 <3.0.0",
                      "resolved": "https://registry.npmjs.org/minipass/-/minipass-2.3.5.tgz"
                    },
                    "minizlib": {
                      "version": "1.2.1",
                      "from": "minizlib@>=1.1.1 <2.0.0",
                      "resolved": "https://registry.npmjs.org/minizlib/-/minizlib-1.2.1.tgz"
                    },
                    "yallist": {
                      "version": "3.0.3",
                      "from": "yallist@>=3.0.2 <4.0.0",
                      "resolved": "https://registry.npmjs.org/yallist/-/yallist-3.0.3.tgz"
                    }
                  }
                }
              }
            }
          }
        },
        "array-flatten": {
          "version": "2.1.2",
          "from": "array-flatten@>=2.1.2 <3.0.0",
          "resolved": "https://registry.npmjs.org/array-flatten/-/array-flatten-2.1.2.tgz"
        },
        "cls-hooked": {
          "version": "4.2.2",
          "from": "cls-hooked@>=4.2.2 <5.0.0",
          "resolved": "https://registry.npmjs.org/cls-hooked/-/cls-hooked-4.2.2.tgz",
          "dependencies": {
            "async-hook-jl": {
              "version": "1.7.6",
              "from": "async-hook-jl@>=1.7.6 <2.0.0",
              "resolved": "https://registry.npmjs.org/async-hook-jl/-/async-hook-jl-1.7.6.tgz",
              "dependencies": {
                "stack-chain": {
                  "version": "1.3.7",
                  "from": "stack-chain@>=1.3.7 <2.0.0",
                  "resolved": "https://registry.npmjs.org/stack-chain/-/stack-chain-1.3.7.tgz"
                }
              }
            }
          }
        },
        "debug-custom": {
          "version": "1.0.6",
          "from": "debug-custom@>=1.0.5 <2.0.0",
          "resolved": "https://registry.npmjs.org/debug-custom/-/debug-custom-1.0.6.tgz",
          "dependencies": {
            "debug": {
              "version": "4.1.1",
              "from": "debug@>=4.1.1 <5.0.0",
              "resolved": "https://registry.npmjs.org/debug/-/debug-4.1.1.tgz"
            }
          }
        },
        "event-pre-handler": {
          "version": "1.0.1",
          "from": "event-pre-handler@>=1.0.1 <2.0.0",
          "resolved": "https://registry.npmjs.org/event-pre-handler/-/event-pre-handler-1.0.1.tgz"
        },
        "glob": {
          "version": "7.1.4",
          "from": "glob@>=7.0.3 <8.0.0",
          "resolved": "https://registry.npmjs.org/glob/-/glob-7.1.4.tgz",
          "dependencies": {
            "fs.realpath": {
              "version": "1.0.0",
              "from": "fs.realpath@>=1.0.0 <2.0.0",
              "resolved": "https://registry.npmjs.org/fs.realpath/-/fs.realpath-1.0.0.tgz"
            },
            "inflight": {
              "version": "1.0.6",
              "from": "inflight@>=1.0.4 <2.0.0",
              "resolved": "https://registry.npmjs.org/inflight/-/inflight-1.0.6.tgz",
              "dependencies": {
                "wrappy": {
                  "version": "1.0.2",
                  "from": "wrappy@>=1.0.0 <2.0.0",
                  "resolved": "https://registry.npmjs.org/wrappy/-/wrappy-1.0.2.tgz"
                }
              }
            },
            "inherits": {
              "version": "2.0.3",
              "from": "inherits@>=2.0.0 <3.0.0",
              "resolved": "https://registry.npmjs.org/inherits/-/inherits-2.0.3.tgz"
            },
            "minimatch": {
              "version": "3.0.4",
              "from": "minimatch@>=3.0.4 <4.0.0",
              "resolved": "https://registry.npmjs.org/minimatch/-/minimatch-3.0.4.tgz",
              "dependencies": {
                "brace-expansion": {
                  "version": "1.1.11",
                  "from": "brace-expansion@>=1.1.7 <2.0.0",
                  "resolved": "https://registry.npmjs.org/brace-expansion/-/brace-expansion-1.1.11.tgz",
                  "dependencies": {
                    "balanced-match": {
                      "version": "1.0.0",
                      "from": "balanced-match@>=1.0.0 <2.0.0",
                      "resolved": "https://registry.npmjs.org/balanced-match/-/balanced-match-1.0.0.tgz"
                    },
                    "concat-map": {
                      "version": "0.0.1",
                      "from": "concat-map@0.0.1",
                      "resolved": "https://registry.npmjs.org/concat-map/-/concat-map-0.0.1.tgz"
                    }
                  }
                }
              }
            },
            "once": {
              "version": "1.4.0",
              "from": "once@>=1.3.0 <2.0.0",
              "resolved": "https://registry.npmjs.org/once/-/once-1.4.0.tgz"
            }
          }
        },
        "methods": {
          "version": "1.1.2",
          "from": "methods@>=1.1.0 <1.2.0",
          "resolved": "https://registry.npmjs.org/methods/-/methods-1.1.2.tgz"
        },
        "minimist": {
          "version": "1.2.0",
          "from": "minimist@>=1.2.0 <2.0.0",
          "resolved": "https://registry.npmjs.org/minimist/-/minimist-1.2.0.tgz"
        },
        "semver": {
          "version": "5.7.0",
          "from": "semver@>=5.0.1 <6.0.0",
          "resolved": "https://registry.npmjs.org/semver/-/semver-5.7.0.tgz"
        },
        "ximmer": {
          "version": "1.2.1",
          "from": "ximmer@>=1.2.1 <2.0.0",
          "resolved": "https://registry.npmjs.org/ximmer/-/ximmer-1.2.1.tgz"
        }
      }
    },
```

`cat /etc/os-release`:
```
NAME="Amazon Linux AMI"
VERSION="2017.09"
ID="amzn"
ID_LIKE="rhel fedora"
VERSION_ID="2017.09"
PRETTY_NAME="Amazon Linux AMI 2017.09"
ANSI_COLOR="0;33"
CPE_NAME="cpe:/o:amazon:linux:2017.09:ga"
HOME_URL="http://aws.amazon.com/amazon-linux-ami/"
```

With `export APPOPTICS_SHOW_OBOE_SETUP=1`, `npm install` in appoptics-bindings has possibly relevant line:
```npm WARN lifecycle appoptics-bindings@6.2.1~install: cannot run in wd %s %s (wd=%s) appoptics-bindings@6.2.1 node setup-liboboe && node-gyp rebuild /var/app/current/node_modules/appoptics-bindings```

Is it possibly the fact that `node-gyp` is not globally installed?

**Comment by bruce-solar** [comment]
the problem is that you are installing while running as root.

see the note on https://docs.appoptics.com/kb/apm_tracing/nodejs/install/

**Comment by bmacnaughton** [comment]
another problem is that node v6.12.2 doesn't support napi.

**Comment by gtilma** [comment]
For posterity, the node version was the root cause as @bmacnaughton says. The first support of napi is in 6.14.3.

**Comment by gtilma** [comment]
Also for posterity, AppOptics support is great :1st_place_medal:
