### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by JoHuang** [appoptics/appoptics-apm-node#7]
I tried yarn and npm.

```
> appoptics-bindings@4.6.2 preinstall /Users/apple/GitProject/xxxxxxxx/node_modules/appoptics-apm/node_modules/appoptics-bindings
> node setup-liboboe

events.js:165
      throw er; // Unhandled 'error' event
      ^

Error: spawn readelf ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:201:19)
    at onErrorNT (internal/child_process.js:379:16)
    at process._tickCallback (internal/process/next_tick.js:178:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:697:11)
    at startup (internal/bootstrap/node.js:201:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:516:3)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:207:12)
    at onErrorNT (internal/child_process.js:379:16)
    [... lines matching original stack trace ...]
    at bootstrapNodeJSCore (internal/bootstrap/node.js:516:3)
```

**Comment by cheempz** [comment]
Hi @JoHuang, thanks for trying out our Node.js agent! 

I'm not sure if your snippet above `/Users/apple` means you're trying to install our agent on Mac OS X, if so, we don't yet support that.  The agent needs to compile a C++ Addon that currently is only supported for Linux -- you can find out more in our KB about [supported platforms](https://docs.appoptics.com/kb/apm_tracing/supported_platforms/) and the Node.js agent[ install dependencies](https://docs.appoptics.com/kb/apm_tracing/nodejs/install/#dependencies).

Side note: If you run Docker containers on your Mac, the agent should install fine in any of the supported Linux containers.  You may need to use the `--unsafe-perm` npm flag if installing as the root user.

**Comment by bmacnaughton** [comment]
JoHuang, thanks for reporting the issue. Did the `--unsafe-perm` flag solve the problem?

I'm going to close this as we haven't heard back but if you still have an issue please re-open it and let us know how we can help.
