### ISSUE TITLE
ao.bind errors in logs

### ISSUE THREAD

**Issue by yo-han** [appoptics/appoptics-apm-node#9]
We just implemented appoptics in a some nodejs servers that we run and found an endless stream of these errors in the logs. We can't find what we're doing wrong here. 

2018-06-18T09:13:17.026Z appoptics:warn instrumentHttp: no last span or disabled
2018-06-18T09:13:17.026Z appoptics:error express.profiledRoute failed to build span
2018-06-18T09:13:17.026Z appoptics:warn instrumentHttp: no last span or disabled
2018-06-18T09:13:17.027Z appoptics:error express.profiledRoute failed to build span
2018-06-18T09:13:17.027Z appoptics:warn instrumentHttp: no last span or disabled
2018-06-18T09:13:17.027Z appoptics:error express.profiledRoute failed to build span
2018-06-18T09:13:17.027Z appoptics:warn instrumentHttp: no last span or disabled
2018-06-18T09:13:17.027Z appoptics:error express.profiledRoute failed to build span
2018-06-18T09:13:17.033Z appoptics:warn instrumentHttp: no last span or disabled
2018-06-18T09:13:17.033Z appoptics:error express.profiledRoute failed to build span
2018-06-18T09:13:17.033Z appoptics:warn instrumentHttp: no last span or disabled
2018-06-18T09:13:17.033Z appoptics:error express.profiledRoute failed to build span
2018-06-18T09:13:17.034Z appoptics:warn instrumentHttp: no last span or disabled
2018-06-18T09:13:17.034Z appoptics:error express.profiledRoute failed to build span
2018-06-18T09:13:17.042Z appoptics:warn ao.bind  - not tracing
2018-06-18T09:13:17.042Z appoptics:warn ao.bind anonymous - not tracing
2018-06-18T09:13:17.042Z appoptics:warn ao.bind undefined - not tracing
2018-06-18T09:13:17.042Z appoptics:warn ao.bind  - not tracing
2018-06-18T09:13:17.042Z appoptics:warn ao.bind  - not tracing
2018-06-18T09:13:17.042Z appoptics:warn ao.bind undefined - not tracing
2018-06-18T09:13:17.043Z appoptics:warn ao.bind  - not tracing
2018-06-18T09:13:17.043Z appoptics:warn ao.bind  - not tracing
2018-06-18T09:13:17.043Z appoptics:warn ao.bind undefined - not tracing
2018-06-18T09:13:17.044Z appoptics:warn ao.bind anonymous - not tracing
2018-06-18T09:13:17.044Z appoptics:warn ao.bind  - not tracing
2018-06-18T09:13:17.044Z appoptics:warn ao.bind undefined - not tracing
2018-06-18T09:13:17.046Z appoptics:warn ao.bind anonymous - not tracing
2018-06-18T09:13:17.046Z appoptics:warn ao.bind anonymous - not tracing
2018-06-18T09:13:17.506Z appoptics:warn ao.bind  - not tracing
2018-06-18T09:13:17.506Z appoptics:warn ao.bind  - not tracing
2018-06-18T09:13:17.506Z appoptics:warn ao.bind undefined - not tracing
2018-06-18T09:13:17.554Z appoptics:warn ao.bind anonymous - not tracing
2018-06-18T09:13:17.554Z appoptics:warn ao.bind anonymous - not tracing
2018-06-18T09:13:18.049Z appoptics:warn ao.bind  - not tracing
2018-06-18T09:13:18.050Z appoptics:warn ao.bind  - not tracing
2018-06-18T09:13:18.050Z appoptics:warn ao.bind undefined - not tracing
2018-06-18T09:13:18.051Z appoptics:warn instrumentHttp: no last span or disabled
2018-06-18T09:13:18.051Z appoptics:error express.profiledRoute failed to build span
2018-06-18T09:13:18.064Z appoptics:warn ao.bind  - no context Error: CLS NOT ACTIVE
    at Object.exports.bind (/usr/src/app/node_modules/appoptics-apm/dist/index.js:555:15)
    at Promise._addCallbacks (/usr/src/app/node_modules/appoptics-apm/dist/probes/bluebird.js:14:31)
    at Promise._then (/usr/src/app/node_modules/bluebird/js/release/promise.js:270:16)
    at Promise.then (/usr/src/app/node_modules/bluebird/js/release/promise.js:125:17)
    at Object.request (/usr/src/app/util/soapclient.js:83:5)
    at /usr/src/app/routes/alteration.js:247:5
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
2018-06-18T09:13:18.065Z appoptics:warn ao.bind anonymous - no context Error: CLS NOT ACTIVE
    at Object.exports.bind (/usr/src/app/node_modules/appoptics-apm/dist/index.js:555:15)
    at Promise._addCallbacks (/usr/src/app/node_modules/appoptics-apm/dist/probes/bluebird.js:14:49)
    at Promise._then (/usr/src/app/node_modules/bluebird/js/release/promise.js:270:16)
    at Promise.then (/usr/src/app/node_modules/bluebird/js/release/promise.js:125:17)
    at Object.request (/usr/src/app/util/soapclient.js:83:5)
    at /usr/src/app/routes/alteration.js:247:5
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
2018-06-18T09:13:18.066Z appoptics:warn ao.bind undefined - no context Error: CLS NOT ACTIVE
    at Object.exports.bind (/usr/src/app/node_modules/appoptics-apm/dist/index.js:555:15)
    at Promise._addCallbacks (/usr/src/app/node_modules/appoptics-apm/dist/probes/bluebird.js:14:66)
    at Promise._then (/usr/src/app/node_modules/bluebird/js/release/promise.js:270:16)
    at Promise.then (/usr/src/app/node_modules/bluebird/js/release/promise.js:125:17)
    at Object.request (/usr/src/app/util/soapclient.js:83:5)
    at /usr/src/app/routes/alteration.js:247:5
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

Are we forgetting something?

**Comment by yo-han** [comment]
I found we could mask these errors by changing the DEBUG env variable to only loggin fatal errors. But that seems not correct way to solve this issue.

**Comment by bmacnaughton** [comment]
Thanks for the bug report.  It seems there is a problem tracing where the context is lost between the HTTP layer and the layers below it.

You're using v5.0.0 of appoptics-apm?

Does your `/usr/src/app/util/soapclient.js` module use `request` or does it use the `http` primitives? If it uses `request`, does it use the promise version?

**Comment by yo-han** [comment]
We're using version 5.0.1 of of appoptics-apm. And the soapclient is using `request v2.87.0`,  the default non promise version.

**Comment by yo-han** [comment]
Node version: 8.11.3
Npm version: 5.6.0
Npm ls: [npm.txt](https://github.com/appoptics/appoptics-apm-node/files/2115169/npm.txt)

In alteration.js on row 247 this request is done:

```
soapclient
.request('Request', args)
.then(
   result => {
	res.json(result);
   },
  reason => {
    res.status(422).json(reason);
  })
.catch(error => {
   next(error);
});
```

Then in soapclient.js the following is executed:

```
// ... some mapping of params in to the args object and method variable

return soap
.createClientAsync(url, { timeout: 30000 })
.then(client => {
	let soapclient = client[method + 'Async'](args);
	return soapclient;
})
.then(
	result => {
		return new Promise((resolve, reject) => {
			if (
				(result[0][method + 'Result'] &&
					result[0][method + 'Result'].Succeeded)
			) {
				resolve(result[0][method + 'Result']);
			} else {
				reject(result[0][method + 'Result']);
			}
		});
	},
	e => {
		console.log(e); 
	}
);
```

**Comment by bmacnaughton** [comment]
Thanks for the additional details. I got to a stopping point in a project and am working to reproduce the issue you've reported.

**Comment by bmacnaughton** [comment]
yo-han, I've got a simple soap-server running and am getting traces so I might be thinking about your application in the wrong way. I have been thinking that it's an HTTP server of some sort that is then making an outbound SOAP call using (something like) the code you provided above. But if that's not the case, and instead it is a batch/cron/command-line initiated process then I'd expect something similar to what you're seeing because the auto-instrumented code doesn't start a trace; you'd have to use the custom-instrumentation `startOrContinueTrace` function to kick things off.

Can you give me a bit of an overview of the structure of your app? I appreciate your help and want to find the issue you're running into.

**Comment by yo-han** [comment]
Yeah I made it so you can use a soap url of your own by passing a SOAP_URL environment variable. When can not share ours because it's a private soap API with authentication.

When you release a new version we can check your fix on our end. I'll let you know what we find out.

**Comment by bmacnaughton** [comment]
Makes sense. Give v5.0.2 a shot when you get a chance. I'm interested in any errors/warnings that remain in your log file (you'll have to turn that back on I guess, at least for a bit).

Thanks for your help; it's always a challenge to debug code without access to it!

**Comment by bmacnaughton** [comment]
I appreciate you reporting this and providing information to help track it down. I'm going to assume that no news is good news and that 5.0.2 addressed the problem. If it didn't, please feel free to comment and we'll reopen this issue.
